import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import yaml from 'yaml'
import type { ParentResource } from '@/gateway/types'
import { config as sharedConfig } from '@/shared/config'

const ROOT_DIR = resolve(__dirname, '../../..')

// Environment configuration
export const env = {
  port: Number(process.env.PORT) || 4000,
  logLevel: sharedConfig.logLevel,
}

// Load supergraph schema (generated by mesh compose)
export const supergraph = readFileSync(resolve(ROOT_DIR, 'src/mesh/gen/supergraph.graphql'), 'utf8')

// Load parent resources configuration
const parentResourcesPath = resolve(ROOT_DIR, 'config/resources/parent-resources.yaml')
export const parentResources = yaml.parse(
  readFileSync(parentResourcesPath, 'utf8')
) as ParentResource[]

// Build a set of valid parent resource combinations for fast lookup
// Format: "apiGroup/version/kind" (kind in lowercase)
export const validParentResources = new Set<string>(
  parentResources.map((p) => `${p.apiGroup}/${p.version}/${p.kind.toLowerCase()}`)
)

// Pre-compute scoped endpoint patterns for documentation
export const scopedEndpoints = Array.from(validParentResources).map((key) => {
  const [apiGroup, version, kind] = key.split('/')
  return `/${apiGroup}/${version}/${kind}s/{name}/graphql`
})

// Build valid kinds from configuration (pluralized, lowercase)
export const validKindsPlural = [
  ...new Set(Array.from(validParentResources).map((key) => key.split('/')[2] + 's')),
]

// URL pattern for scoped resources - built dynamically from config
export const SCOPED_RESOURCE_PATTERN =
  validKindsPlural.length > 0
    ? new RegExp(`^/([^/]+)/([^/]+)/(${validKindsPlural.join('|')})/([^/]+)/graphql$`)
    : null

// All available endpoints for documentation
export const availableEndpoints = ['/graphql', '/healthcheck', '/readiness', ...scopedEndpoints]
